# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: postgresql
#   database: itunes-library
#   pool: 5
#   timeout: 5000

development:
  adapter: mysql2
  database: itunes_library
  username: itunes_library
  password: itunes_library
  host: localhost
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: itunes_library_test
  username: itunes_library
  password: itunes_library
  host: localhost
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
